### ISSUE TITLE
"gear" does not exist

### ISSUE THREAD

**Issue by sjanssen2** [JonasKup/FlowSoFineApp#1]
On my Linux machine, within a conda envrionment with R 4.1.1, I am getting the error `This Font Awesome icon ('gear') does not exist`. Can we therefore replace this icon with e.g. "cog"? See https://fontawesome.com/v5.15/icons?d=gallery&p=2&q=gear
https://github.com/JonasKup/FlowSoFineApp/blob/403591e8b334c09e919e911c85f94f770162e229/inst/shiny-app/FlowSoFineApp/R/tscores_tab.R#L26

**Comment by JonasKup** [comment]
Done!
