### ISSUE TITLE
advance screen

### ISSUE THREAD

**Issue by sjanssen2** [JonasKup/FlowSoFineApp#12]
Once both steps were computed, we should let the user know that the system is ready for analysis. 
![image](https://user-images.githubusercontent.com/11960616/136380603-bcdc7d0e-ba01-4cd8-acc0-3f4db200a1bc.png)
Can we therefore advance to some other page, like "visualizations"? Or show the left menu?

**Comment by JonasKup** [comment]
Added "continue" button that appears when template and distance matrix are calculated

![grafik](https://user-images.githubusercontent.com/53520351/136693570-e1fb9ce0-be52-456e-8af1-8cd11e0bd8e1.png)
