### ISSUE TITLE
Sample Names

### ISSUE THREAD

**Issue by sjanssen2** [JonasKup/FlowSoFineApp#8]
I very much like the view of the raw sample data, however it isn't easy to select the correct item from the table on the right hand site. Can we have the sample name instead of a numeric index as the first column?
![image](https://user-images.githubusercontent.com/11960616/136375791-849ab70a-de6a-4f9c-baa6-2e5e327fb2df.png)

**Comment by sjanssen2** [comment]
scratch that, I think I used a wrong metadata file. But can you please double check, that the "index column" which is the leftmost column, is here always displayed leftmost (except of the numeric counter)?

**Comment by JonasKup** [comment]
The rownames of the metadata table are now automatically renamed to the sample names and show up instead of the numeric counter
![grafik](https://user-images.githubusercontent.com/53520351/136694347-8a6f5947-0e3c-49dc-9efe-c67e74452320.png)
